In [ ]:
import numpy as np

In [ ]:
import torch
import sympy

In [ ]:
!pip install torch torchvision -U

Data structures organises data in different forms (List, Tuple, Array)

Tensor (data structure) = Layer of arrays in x dimension





In [ ]:
#1D tensor

tensor_1D = torch.tensor([1,2,3,4,5,6,7,8,9,10])
tensor_1D

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#2D tensor

tensor_2D = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
tensor_2D

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
#2D tensor with zeroes

tensor_2D = torch.tensor([[0,0,0],[0,0,0]])
tensor_2D

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
#2D tensor with zeroes

tensor_zeros = torch.zeros(2,3)
tensor_zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
#2D tensor with ones

tensor_ones = torch.ones(2,3)
tensor_ones

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
#3D tensor

tensor_3D = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
tensor_3D

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
tensor_3D.shape

torch.Size([3, 3])

In [ ]:
#Empty gives random values or zeros

tensor_3D = torch.empty(2,2,3)
tensor_3D

tensor([[[7.4144e-04, 4.5597e-41, 1.7994e-33],
         [0.0000e+00, 1.3737e+06, 4.5595e-41]],

        [[3.6538e-04, 4.5597e-41, 1.3741e+06],
         [4.5595e-41, 3.6538e-04, 4.5597e-41]]])

In [ ]:
tensor_3D.shape

torch.Size([2, 2, 3])

##Number of square brackets before the curly brace indicates the dimension of the tensor

In [ ]:
#Mathematical operation on a 2D tensor

tensor_2D_math = tensor_2D * 2
tensor_2D_math

tensor([[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]])

In [ ]:
#Converting numpy array to a tensor

np_array = np.array([1,2,3,4,5,6,7,8,9,10])
tensor_np = torch.from_numpy(np_array)
tensor_np

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#Converting tensor to numpy array

np_array_tensor = tensor_np.numpy()
np_array_tensor

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
torch.tensor(a, dtype=torch.int8)
torch.tensor(5, dtype=torch.int8)

tensor(5, dtype=torch.int8)

In [ ]:
# torch.tensor(a)
tensor_0D = torch.tensor([[5]])
tensor_0D.size()

torch.Size([1, 1])

In [ ]:
#Attribute = size (property)
#Function = size()

In [ ]:
type(tensor_0D)

torch.Tensor

In [ ]:
tensor_0D.shape

torch.Size([1, 1])

In [ ]:
# Create a 3D tensor of size (2,2,3) with random numbers between 0 and 1
tensor_3d = torch.rand(2,2,3)

# Print the tensor
print(tensor_3d)

tensor([[[0.7176, 0.9270, 0.9908],
         [0.3587, 0.5408, 0.3632]],

        [[0.0256, 0.2451, 0.3157],
         [0.4000, 0.5044, 0.1897]]])


In [ ]:
#Convert the 3d array to a 2d array
tensor_2d = tensor_3d.reshape(tensor_3d.shape[0], -1)
print(tensor_2d.shape)

torch.Size([2, 6])


In [ ]:
#Make a 3d tensor using all unique prime numbers from 1 to 100

primes = list(sympy.primerange(1, 101))

num_primes = len(primes)
print(f"Number of primes: {num_primes}")
print(f"Primes: {primes}")

prime_tensor = torch.tensor(primes)

shape = (1, 5, 5)

prime_tensor = prime_tensor[:shape[0] * shape[1] * shape[2]].reshape(shape)

print(prime_tensor)


Number of primes: 25
Primes: [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]
tensor([[[ 2,  3,  5,  7, 11],
         [13, 17, 19, 23, 29],
         [31, 37, 41, 43, 47],
         [53, 59, 61, 67, 71],
         [73, 79, 83, 89, 97]]])
